  language: python
  python:
    - "3.6"
  before_install:
   - export PYTHONPATH=$HOME/builds/practical-recommender-systems/moviegeek/
  install:
  - pip3 install -r requirements.txt
  script: python -m pytest ./test/